import type { Metadata } from 'next';

/**
 * Central SEO config + helpers. One source of truth for the canonical domain,
 * per-page metadata (title/description/canonical/OG/Twitter), and JSON-LD builders.
 * Public marketing pages are client components, so each gets a tiny server layout.tsx
 * that calls `pageMetadata()`.
 */

export const SITE = {
  name: 'SABI',
  url: (process.env.NEXT_PUBLIC_APP_URL || 'https://sability.io').replace(/\/$/, ''),
  tagline: "Nigeria's Social Infrastructure",
  description:
    'The social media growth platform powered by 300,000 real Nigerians. Real followers, likes, views and comments across 11 platforms, targetable by state, city and gender. Orders start within minutes.',
  // Global OG image is generated by app/opengraph-image.tsx (1200×630, branded).
} as const;

type PageMetaInput = {
  /** Page-specific title; the root template appends " · SABI". */
  title: string;
  description: string;
  /** Absolute path from the site root, e.g. "/sabi/services". */
  path: string;
  keywords?: string;
  /** Longer/marketing OG title; defaults to `title`. */
  ogTitle?: string;
  /** Set on auth-gated or thin pages we don't want in the index. */
  noIndex?: boolean;
};

/** Build consistent per-page metadata with a canonical URL. OG/Twitter images are
 *  inherited from the site-wide app/opengraph-image.tsx, so we don't set them here. */
export function pageMetadata(input: PageMetaInput): Metadata {
  const url = SITE.url + input.path;
  return {
    title: input.title,
    description: input.description,
    ...(input.keywords ? { keywords: input.keywords } : {}),
    alternates: { canonical: url },
    openGraph: {
      title: input.ogTitle || `${input.title} · ${SITE.name}`,
      description: input.description,
      url,
      siteName: SITE.name,
      type: 'website',
    },
    twitter: {
      card: 'summary_large_image',
      title: input.ogTitle || `${input.title} · ${SITE.name}`,
      description: input.description,
    },
    robots: input.noIndex
      ? { index: false, follow: false, googleBot: { index: false, follow: false } }
      : { index: true, follow: true },
  };
}

/* ------------------------------ JSON-LD builders ------------------------------ */

export function organizationLd() {
  return {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: SITE.name,
    legalName: 'SABI',
    url: SITE.url,
    logo: `${SITE.url}/sabi-logo-main.png`,
    description: SITE.description,
    areaServed: { '@type': 'Country', name: 'Nigeria' },
    slogan: SITE.tagline,
  };
}

export function websiteLd() {
  return {
    '@context': 'https://schema.org',
    '@type': 'WebSite',
    name: SITE.name,
    url: SITE.url,
    description: SITE.description,
    inLanguage: 'en-NG',
    potentialAction: {
      '@type': 'SearchAction',
      target: { '@type': 'EntryPoint', urlTemplate: `${SITE.url}/sabi/services?q={search_term_string}` },
      'query-input': 'required name=search_term_string',
    },
  };
}

/** A "Service" node — used on the services/landing pages so SABI can surface as an
 *  offering for social-growth queries. */
export function serviceLd() {
  return {
    '@context': 'https://schema.org',
    '@type': 'Service',
    serviceType: 'Social media growth & engagement',
    provider: { '@type': 'Organization', name: SITE.name, url: SITE.url },
    areaServed: { '@type': 'Country', name: 'Nigeria' },
    description:
      'Real followers, likes, views, comments, shares and subscribers from verified Nigerians across Instagram, TikTok, YouTube, X, Facebook and more — targetable by state, city and gender.',
    url: `${SITE.url}/sabi/services`,
  };
}

export function breadcrumbLd(items: { name: string; path: string }[]) {
  return {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: items.map((it, i) => ({
      '@type': 'ListItem',
      position: i + 1,
      name: it.name,
      item: SITE.url + it.path,
    })),
  };
}

export function faqLd(qa: { q: string; a: string }[]) {
  return {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: qa.map(({ q, a }) => ({
      '@type': 'Question',
      name: q,
      acceptedAnswer: { '@type': 'Answer', text: a },
    })),
  };
}
